version: "3.9"
services:
  app-sinapsis:
    image: gabyreload1983/app-sinapsis:vx.x.x
    container_name: app-sinapsis-vx.x.x
    ports:
      - "3333:3333"
    restart: on-failure
    environment:
      - JWT_PRIVATE_KEY=
      - MONGO_CREDENTIALS=
      - URBANO_HOST=
      - URBANO_DB=
      - URBANO_PASS=
      - URBANO_USER=
      - TICKET_HOST=
      - TICKET_DB=
      - TICKET_PASS=
      - TICKET_USER=
      - PORT=
      - MAIL_HOST=
      - MAIL_USER=
      - MAIL_PASSWORD=
      - MAIL_FROM=
      - MAIL_BCC=
      - NODE_ENV=
